name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
      - 'release.*'

jobs:
  # --- Stage: test ---
  install_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run install env script
        run: echo "test 1 -----------------------------------------"

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests script
        run: echo "test 2 -----------------------------------------"

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linter script
        run: echo "test linter-------------------------------------"
      # Чистая заглушка проверки index.html
      - name: Check index.html
        run: echo "index.html найден, файл готов к сборке."

  # --- Stage: build ---
  build:
    needs: [install_env, run_tests, linters]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build script
        run: echo "running ./build.sh (заглушка)"

  # --- Stage: test2 ---
  tests_after_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests after build
        run: echo "test after build 1 ---------------------------------"

  # --- Stage: dev ---
  deploy_dev:
    needs: tests_after_build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy dev script
        run: echo "running ./build.sh (заглушка деплоя в dev)"

  # --- Stage: stage ---
  deploy_stage:
    needs: tests_after_build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deploy stage script
        run: echo "running ./build.sh (заглушка деплоя в stage)"
